build:
  - name: Build and Deploy
    script:
      - /opt/render/project/src/.venv/bin/python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt  # Replace with this command

web:
  - buildCommand: "python -m pip install -r requirements.txt"
    port: 5000  # Use the port you specified in your Flask app
